#!/bin/sh -el
VERSION=${VERSION:-0.$(date +%Y%m%d%H%M)}

ci=
while test $# -gt 0; do
  case "$1" in
    -v)
      VERSION=$2;;
    --ci)
      ci=true;;
  esac
  shift
done

rm -f debian/changelog
dch --create --package repo-clean -v $VERSION ""
if [ -z "$ci" ]; then
  ./debian/rules clean
  ./debian/rules build
  fakeroot ./debian/rules binary OUTDIR=.
else
  docker build -f Docker-build -t repoclean-build .
  docker run --rm -t -v $PWD:/mnt repoclean-build
fi
